name: worldbooks
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/wb_logo.png
   - assets/images/wave-haikei.png
   - assets/images/wave-haikei-2.png
   - assets/images/blob-scene-haikei.png
   - assets/images/blob-haikei-2.png
   - assets/images/layered-waves-haikei.png
   - assets/images/layered-waves-haikei-2.png
   - assets/images/layered-waves-haikei-3.png
   - assets/images/cat_cover.jpg
   - assets/images/categorias/romance.png
   - assets/images/categorias/terror.png
   - assets/images/categorias/acao.png
   - assets/images/categorias/misterio.png
   - assets/images/categorias/aventura.png
   - assets/images/categorias/comedia.png
   - assets/images/categorias/fantasia.png
   - assets/images/categorias/ficcao_cientifica.png
   - assets/images/categorias/suspense.png
   - assets/images/categorias/drama.png

  #  JSONS
   - assets/data/book_detailed_data.json
   - assets/data/books_list_data.json
   - assets/data/categoria_data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        # - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        # - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        # - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        # - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
